FROM nginx:alpine
COPY index.html /templates/index.html
COPY nginx.conf /etc/nginx/conf.d/default.conf
CMD ["/bin/sh", "-c", "envsubst '$$WHEP_URL' < /templates/index.html > /usr/share/nginx/html/index.html && nginx -g 'daemon off;'"]
