# docker-compose.yml
services:
  mediamtx:
    build:
      context: .
      dockerfile: Dockerfile.mediamtx
    restart: unless-stopped
    volumes:
      - recordings:/recordings
    ports:
     - 1935:1935   # RTMP
     - 8889:8889   # WebRTC HTTP
     - 8189:8189/udp  # WebRTC UDP (if needed)

  player:
    build:
      context: .
      dockerfile: Dockerfile.player
    restart: unless-stopped
    ports:
      - "8080:80"
    environment:
      WHEP_URL: http://localhost:8889/live_webrtc/whep

volumes:
  recordings:
